name: Run Jest Tests and Coverage

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Jest tests and generate coverage report
      - name: Run Jest tests with coverage
        run: npm test -- --coverage

      # Use Jest coverage report action to publish coverage results
      - name: Report Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm test
