name: Run Jest Tests and Coverage

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Jest globally
      - name: Install Jest globally
        run: npm install -g jest

      # Log Jest Configuration
      - name: Log Jest Configuration
        run: npx jest --showConfig

      # Run Jest tests with coverage
      - name: Run Jest tests with coverage
        run: CI=true npm test -- --coverage

      # List contents of the root directory for debugging
      - name: List root directory
        run: ls -la

      # List coverage directory for debugging
      - name: List coverage directory
        run: ls -R coverage/ || echo "Coverage directory not found"

      # Upload coverage report for inspection
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      # Publish Jest coverage results
      - name: Report Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage/lcov.info
